# Generated by Django 6.0.3 on 2026-04-14 19:44

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("anagrafica", "0018_alter_socio_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verbale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data del verbale")),
                (
                    "numero_progressivo",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="Numero progressivo"
                    ),
                ),
                (
                    "consiglio_direttivo",
                    models.TextField(
                        blank=True,
                        help_text="Nomi e cognomi dei membri del consiglio direttivo.",
                        verbose_name="Consiglio direttivo",
                    ),
                ),
                (
                    "soci",
                    models.ManyToManyField(
                        blank=True,
                        related_name="verbali",
                        to="anagrafica.socio",
                        verbose_name="Soci presenti",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verbale",
                "verbose_name_plural": "Verbali",
                "ordering": ["-data", "-numero_progressivo"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.datetime.ExtractYear("data"),
                        models.F("numero_progressivo"),
                        name="unique_progressivo_per_year",
                    )
                ],
            },
        ),
    ]
