# Generated by Django 6.0.3 on 2026-04-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0018_alter_socio_tipo"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oggetto", models.CharField(max_length=200, verbose_name="Oggetto")),
                ("corpo", models.TextField(verbose_name="Corpo email (HTML)")),
                (
                    "destinatari",
                    models.CharField(
                        choices=[
                            ("tutti", "Tutti i soci (con consenso)"),
                            ("in_regola", "Solo soci in regola"),
                            ("scaduti", "Solo soci con quota scaduta"),
                        ],
                        default="tutti",
                        max_length=20,
                        verbose_name="Destinatari",
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[("bozza", "Bozza"), ("inviata", "Inviata")],
                        default="bozza",
                        editable=False,
                        max_length=10,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "data_invio",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Data invio"
                    ),
                ),
                (
                    "num_destinatari",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="N° destinatari"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Newsletter",
                "verbose_name_plural": "Newsletter",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="verbale",
            name="soci",
            field=models.ManyToManyField(
                blank=True,
                related_name="verbali",
                to="anagrafica.socio",
                verbose_name="Soci ammessi",
            ),
        ),
    ]
