# Generated by Django 6.0.3 on 2026-03-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Soci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("cognome", models.CharField(max_length=100, verbose_name="Cognome")),
                ("data_nascita", models.DateField(verbose_name="Data di nascita")),
                ("luogo_nascita", models.CharField(verbose_name="Luogo di nascita")),
                (
                    "codice_fiscale",
                    models.CharField(max_length=16, verbose_name="Codice Fiscale"),
                ),
                (
                    "indirizzo",
                    models.CharField(
                        max_length=200, verbose_name="Indirizzo di residenza"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
            ],
        ),
    ]
