# Generated by Django 6.0.3 on 2026-03-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Socio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("cognome", models.CharField(max_length=100, verbose_name="Cognome")),
                ("data_nascita", models.DateField(verbose_name="Data di nascita")),
                (
                    "luogo_nascita",
                    models.CharField(max_length=100, verbose_name="Luogo di nascita"),
                ),
                (
                    "codice_fiscale",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Codice Fiscale"
                    ),
                ),
                (
                    "indirizzo",
                    models.CharField(
                        max_length=200, verbose_name="Indirizzo di residenza"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data di registrazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ultimo aggiornamento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Socio",
                "verbose_name_plural": "Soci",
                "ordering": ["cognome", "nome"],
            },
        ),
        migrations.DeleteModel(
            name="Soci",
        ),
    ]
