# Generated by Django 6.0.3 on 2026-03-05 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0002_socio_delete_soci"),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="soci/qrcodes/", verbose_name="QR Code"
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Token di verifica",
            ),
        ),
        migrations.CreateModel(
            name="Quota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.PositiveIntegerField(verbose_name="Anno")),
                (
                    "importo",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Importo (€)"
                    ),
                ),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("pagata", "Pagata"),
                            ("in_attesa", "In attesa di pagamento"),
                            ("annullata", "Annullata"),
                        ],
                        default="in_attesa",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data pagamento"
                    ),
                ),
                ("data_inizio", models.DateField(verbose_name="Inizio validità")),
                ("data_scadenza", models.DateField(verbose_name="Scadenza")),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote",
                        to="anagrafica.socio",
                        verbose_name="Socio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quota",
                "verbose_name_plural": "Quote",
                "ordering": ["-anno"],
                "unique_together": {("socio", "anno")},
            },
        ),
    ]
