# Generated by Django 6.0.3 on 2026-03-10 23:46

import anagrafica.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0003_socio_qr_code_socio_token_quota"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quota",
            options={
                "ordering": ["-anno"],
                "verbose_name": "Quota Associativa",
                "verbose_name_plural": "Quote Associative",
            },
        ),
        migrations.AddField(
            model_name="socio",
            name="approvato",
            field=models.BooleanField(
                default=True,
                help_text="Se deselezionato, il socio è in attesa di approvazione.",
                verbose_name="Approvato",
            ),
        ),
        migrations.AlterField(
            model_name="socio",
            name="codice_fiscale",
            field=models.CharField(
                max_length=16,
                unique=True,
                validators=[anagrafica.models.valida_codice_fiscale],
                verbose_name="Codice Fiscale",
            ),
        ),
    ]
