# Generated by Django 6.0.3 on 2026-03-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0004_alter_quota_options_socio_approvato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="consenso_marketing",
            field=models.BooleanField(
                default=False,
                help_text="Il socio ha acconsentito a ricevere comunicazioni promozionali.",
                verbose_name="Consenso marketing",
            ),
        ),
    ]
