# Generated by Django 6.0.3 on 2026-03-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0005_socio_consenso_marketing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quota",
            name="data_inizio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Inizio validità"
            ),
        ),
        migrations.AlterField(
            model_name="quota",
            name="data_scadenza",
            field=models.DateField(blank=True, null=True, verbose_name="Scadenza"),
        ),
    ]
