# Generated by Django 6.0.3 on 2026-03-11 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0006_alter_quota_data_inizio_alter_quota_data_scadenza"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quota",
            name="note",
        ),
    ]
