# Generated by Django 6.0.3 on 2026-03-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0007_remove_quota_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="consenso_immagini",
            field=models.BooleanField(
                default=False, verbose_name="Consenso uso immagini"
            ),
        ),
        migrations.AlterField(
            model_name="socio",
            name="consenso_marketing",
            field=models.BooleanField(
                default=False, verbose_name="Consenso newsletter e comunicazioni"
            ),
        ),
    ]
