# Generated by Django 6.0.3 on 2026-03-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0008_socio_consenso_immagini_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="firma",
            field=models.TextField(blank=True, null=True, verbose_name="Firma"),
        ),
    ]
