# Generated by Django 6.0.3 on 2026-03-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0009_socio_firma"),
    ]

    operations = [
        migrations.AddField(
            model_name="quota",
            name="pdf_iscrizione",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="soci/pdf/",
                verbose_name="PDF iscrizione",
            ),
        ),
    ]
