# Generated by Django 6.0.3 on 2026-03-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0010_quota_pdf_iscrizione"),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefono"
            ),
        ),
    ]
