# Generated by Django 6.0.3 on 2026-03-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0011_socio_telefono"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socio",
            name="indirizzo",
        ),
        migrations.AddField(
            model_name="socio",
            name="cap",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="CAP"
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="comune",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Comune"
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="provincia",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Provincia"
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="via",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Via/Piazza"
            ),
        ),
    ]
