# Generated by Django 6.0.3 on 2026-03-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0012_remove_socio_indirizzo_socio_cap_socio_comune_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socio",
            name="cap",
            field=models.CharField(max_length=5, verbose_name="CAP"),
        ),
        migrations.AlterField(
            model_name="socio",
            name="comune",
            field=models.CharField(max_length=100, verbose_name="Comune"),
        ),
        migrations.AlterField(
            model_name="socio",
            name="provincia",
            field=models.CharField(max_length=2, verbose_name="Provincia"),
        ),
        migrations.AlterField(
            model_name="socio",
            name="via",
            field=models.CharField(max_length=200, verbose_name="Via/Piazza"),
        ),
    ]
