# Generated by Django 6.0.3 on 2026-03-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0013_alter_socio_cap_alter_socio_comune_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("VP", "Vice Presidente"),
                    ("CO", "Consigliere"),
                    ("SG", "Segretario"),
                    ("DS", "Direttore Sportivo"),
                    ("GA", "Giudice Arbitro"),
                    ("MS", "Medico Sportivo"),
                    ("SO", "Socio Ordinario"),
                    ("SJ", "Socio Junior"),
                    ("AT", "Atleta"),
                ],
                default="SO",
                max_length=2,
                verbose_name="Tipo socio",
            ),
        ),
    ]
