# Generated by Django 6.0.3 on 2026-03-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0014_socio_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="tutore_codice_fiscale",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                verbose_name="Codice Fiscale tutore",
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="tutore_cognome",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Cognome tutore"
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="tutore_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email tutore"
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="tutore_nome",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nome tutore"
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="tutore_telefono",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefono tutore"
            ),
        ),
    ]
