# Generated by Django 6.0.3 on 2026-03-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "anagrafica",
            "0015_socio_tutore_codice_fiscale_socio_tutore_cognome_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="tutore_residenza",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Residenza tutore"
            ),
        ),
    ]
