# Generated by Django 6.0.3 on 2026-03-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0016_socio_tutore_residenza"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quota",
            name="pdf_iscrizione",
        ),
        migrations.AlterField(
            model_name="socio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("SS", "Socio Sostenitore"),
                    ("VP", "Vice Presidente"),
                    ("CO", "Consigliere"),
                    ("SG", "Segretario"),
                    ("DS", "Direttore Sportivo"),
                    ("GA", "Giudice Arbitro"),
                    ("MS", "Medico Sportivo"),
                    ("SO", "Socio Ordinario"),
                    ("SJ", "Socio Junior"),
                    ("AT", "Atleta"),
                ],
                default="SS",
                max_length=2,
                verbose_name="Tipo socio",
            ),
        ),
    ]
