# Generated by Django 6.0.3 on 2026-04-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0017_remove_quota_pdf_iscrizione_alter_socio_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socio",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("SS", "Socio Sostenitore"),
                    ("SV", "Socio Volontario"),
                    ("VP", "Vice Presidente"),
                    ("PS", "Presidente"),
                    ("CO", "Consigliere"),
                    ("SG", "Segretario"),
                    ("TE", "Tesoriere"),
                ],
                default="SS",
                max_length=2,
                verbose_name="Tipo socio",
            ),
        ),
    ]
