# Generated by Django 6.0.3 on 2026-04-18 15:42

import anagrafica.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0018_alter_socio_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="numero_documento",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Numero documento"
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="tipo_documento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("passaporto", "Passaporto"),
                    ("carta_identita", "Carta di identità"),
                    ("patente", "Patente di guida"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo documento",
            ),
        ),
        migrations.AlterField(
            model_name="socio",
            name="codice_fiscale",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                unique=True,
                validators=[anagrafica.models.valida_codice_fiscale],
                verbose_name="Codice Fiscale",
            ),
        ),
    ]
