# Generated by Django 6.0.3 on 2026-05-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0019_add_documento_alternativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="nazione",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Nazione"
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="residente_estero",
            field=models.BooleanField(
                default=False, verbose_name="Residente all'estero"
            ),
        ),
        migrations.AlterField(
            model_name="socio",
            name="cap",
            field=models.CharField(max_length=10, verbose_name="CAP/Codice postale"),
        ),
        migrations.AlterField(
            model_name="socio",
            name="comune",
            field=models.CharField(max_length=100, verbose_name="Comune/Città"),
        ),
        migrations.AlterField(
            model_name="socio",
            name="provincia",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Provincia/Stato"
            ),
        ),
    ]
