# Generated by Django 6.0.3 on 2026-03-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("anagrafica", "0014_socio_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configurazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_associazione",
                    models.CharField(max_length=200, verbose_name="Nome associazione"),
                ),
                (
                    "via",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Via/Piazza"
                    ),
                ),
                (
                    "comune",
                    models.CharField(blank=True, max_length=100, verbose_name="Comune"),
                ),
                (
                    "provincia",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Provincia"
                    ),
                ),
                ("cap", models.CharField(blank=True, max_length=5, verbose_name="CAP")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="configurazione/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "delta_giorni_iscrizione",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Numero di giorni di validità dell'iscrizione.",
                        verbose_name="Delta giorni iscrizione",
                    ),
                ),
                (
                    "delta_giorni_registro",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Numero di giorni per il registro.",
                        verbose_name="Delta giorni registro",
                    ),
                ),
                (
                    "consiglio_direttivo",
                    models.ManyToManyField(
                        blank=True,
                        related_name="consigli",
                        to="anagrafica.socio",
                        verbose_name="Membri del consiglio direttivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configurazione",
                "verbose_name_plural": "Configurazione",
            },
        ),
    ]
