# Generated by Django 6.0.3 on 2026-03-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anagrafica", "0014_socio_tipo"),
        ("configurazione", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configurazione",
            name="consiglio_direttivo",
            field=models.ManyToManyField(
                blank=True,
                related_name="consiglieri",
                to="anagrafica.socio",
                verbose_name="Membri del consiglio direttivo",
            ),
        ),
    ]
