# Generated by Django 6.0.3 on 2026-03-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurazione", "0002_alter_configurazione_consiglio_direttivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurazione",
            name="cf",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Codice Fiscale"
            ),
        ),
    ]
