# Generated by Django 6.0.3 on 2026-03-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurazione", "0003_configurazione_cf"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurazione",
            name="pec",
            field=models.EmailField(blank=True, max_length=254, verbose_name="PEC"),
        ),
    ]
