# Generated by Django 6.0.3 on 2026-03-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurazione", "0004_configurazione_pec"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurazione",
            name="firma_presidente",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="configurazione/firme/",
                verbose_name="Firma del presidente",
            ),
        ),
    ]
