# Generated by Django 6.0.3 on 2026-03-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurazione", "0005_configurazione_firma_presidente"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurazione",
            name="logo_secondario",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="configurazione/",
                verbose_name="Logo secondario",
            ),
        ),
    ]
