# Generated by Django 6.0.3 on 2026-04-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurazione", "0006_configurazione_logo_secondario"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurazione",
            name="scadenza_quota_giorno",
            field=models.PositiveSmallIntegerField(
                default=31,
                help_text="Giorno di scadenza della quota associativa.",
                verbose_name="Giorno scadenza quota",
            ),
        ),
        migrations.AddField(
            model_name="configurazione",
            name="scadenza_quota_mese",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Mese di scadenza della quota associativa.",
                verbose_name="Mese scadenza quota",
            ),
        ),
    ]
