# Generated by Django 6.0.3 on 2026-04-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurazione", "0007_configurazione_scadenza_quota_giorno_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configurazione",
            name="scadenza_quota_giorno",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Giorno di scadenza della quota associativa.",
                verbose_name="Giorno scadenza quota",
            ),
        ),
        migrations.AlterField(
            model_name="configurazione",
            name="scadenza_quota_mese",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Mese di scadenza della quota associativa.",
                verbose_name="Mese scadenza quota",
            ),
        ),
    ]
