# Generated by Django 6.0.3 on 2026-04-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configurazione", "0008_alter_configurazione_scadenza_quota_giorno_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configurazione",
            name="scadenza_quota_giorno",
            field=models.PositiveSmallIntegerField(
                default=31,
                help_text="Giorno di scadenza della quota associativa.",
                verbose_name="Giorno scadenza quota",
            ),
        ),
    ]
